version: '3.8'

services:
  web:
    build: 
      context: ./nexusapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
